site_name: libpybee — Docs
site_url: https://dyl-m.github.io/libpybee
site_description: Documentation for libpybee, Python
repo_url: https://github.com/Dyl-M/libpybee

nav:
    -   Introduction: index.md
    -   Changelog: changelog.md

theme:
    name: material
    features:
        - navigation.tabs
        - navigation.sections
        - toc.integrate
        - navigation.top
        - search.suggest
        - search.highlight
        - content.tabs.link
        - content.code.annotation
        - content.code.copy
    language: en
    palette:
        -   scheme: slate
            toggle:
                icon: material/toggle-switch
                name: Switch to light mode
            primary: amber
            accent: yellow

        -   scheme: default
            toggle:
                icon: material/toggle-switch-off-outline
                name: Switch to dark mode
            primary: amber
            accent: yellow

extra:
    social:
        -   icon: fontawesome/brands/github-alt
            link: https://github.com/Dyl-M
        -   icon: fontawesome/brands/twitter
            link: https://x.com/dyl_m_tweets
        -   icon: fontawesome/brands/linkedin
            link: https://www.linkedin.com/in/dylan-monfret/

markdown_extensions:
    - codehilite
    -   pymdownx.highlight:
            anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - admonition
    -   pymdownx.arithmatex:
            generic: true
    - footnotes
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.mark
    - attr_list
    -   pymdownx.emoji:
            emoji_index: !!python/name:materialx.emoji.twemoji
            emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
    &copy; 2024 <a href="https://github.com/Dyl-M"  target="_blank" rel="noopener">Dylan Monfret</a>