name: 🕷️ Issue Report
description: Create a report to indicate a problem with `libpybee`
labels: [bug]
body:

    -   type: textarea
        id: reproduce-steps
        attributes:
            label: Steps to reproduce
            description: Sequence of events leading to the behavior.
            placeholder: |
                Example:
                    1. Importing `Library` from `libpybee`
                    2. Calling X function with on Y argument on `Track` object
                    3. Leading to following error: `<ERROR_CODE>`
        validations:
            required: true

    -   type: textarea
        id: expected-behavior
        attributes:
            label: Expected behavior
            description: A clear and concise description of what you expected to happen.
            placeholder: |
                Example:
                  "This should happen..."
        validations:
            required: true

    -   type: textarea
        id: actual-behavior
        attributes:
            label: Actual behavior
            description: A clear and concise description of what what actually happens (include Error codes).
            placeholder: |
                Example:
                  "This happened instead..."
        validations:
            required: true

    -   type: textarea
        id: other-details
        attributes:
            label: Other details
            placeholder: |
                Additional details and attachments.

    -   type: checkboxes
        id: acknowledgements
        attributes:
            label: Acknowledgements
            description: Read this carefully, the issue will be closes and ignore if you skimmed through this.
            options:
                -   label: I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
                    required: true
                -   label: I have written a short but informative title.
                    required: true
                -   label: I have filled out all of the requested information in this form.
                    required: true